---
title: "meta_sem"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## librarying packages

```{r, httr and meta}
library(httr) # call data from github
library(meta) # call meta analysis
```

## Data 

```{r librarying}


df1<-read.csv("http://raw.githubusercontent.com/SangbuemCho/meta_sem/master/meta_sd.csv", 
             header = T, stringsAsFactors = F)
df2<-read.csv("http://raw.githubusercontent.com/SangbuemCho/meta_sem/master/meta_sem.csv", 
              header = T, stringsAsFactors = F)
df1
df2
```

## Meta analysis

```{r meta}

meta1<-metacont(n.e, mean.e, sd.e, n.c, mean.c, sd.c, data=df1, sm="SMD", studlab=paste(study))
meta2<-metacont(n.e, mean.e, sd.e, n.c, mean.c, sd.c, data=df2, sm="SMD", studlab=paste(study))
meta1
meta2

```

## Forest plot

You can also embed plots, for example:

```{r forestplot, echo=FALSE}
forest(meta1)
forest(meta2)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
